/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FundType = IDL.Variant({
  'mix' : IDL.Null,
  'gaming' : IDL.Null,
  'stock' : IDL.Null,
  'political' : IDL.Null,
});
export const Time = IDL.Int;
export const FundActivation = IDL.Record({
  'usedByUserId' : IDL.Opt(IDL.Text),
  'code' : IDL.Text,
  'createdAt' : Time,
  'isUsed' : IDL.Bool,
  'fundType' : FundType,
});
export const AccountStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const BankAccount = IDL.Record({
  'status' : AccountStatus,
  'ifscCode' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'bankName' : IDL.Text,
  'accountType' : IDL.Text,
  'upiId' : IDL.Text,
  'accountNumber' : IDL.Text,
  'accountHolder' : IDL.Text,
});
export const TransactionType = IDL.Variant({
  'credit' : IDL.Null,
  'debit' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CommissionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
});
export const CommissionMethod = IDL.Variant({
  'upi' : IDL.Null,
  'usdt' : IDL.Null,
  'bankTransfer' : IDL.Null,
});
export const CommissionWithdrawal = IDL.Record({
  'id' : IDL.Text,
  'status' : CommissionStatus,
  'method' : CommissionMethod,
  'userId' : IDL.Text,
  'approvedAt' : IDL.Opt(Time),
  'createdAt' : Time,
  'amount' : IDL.Nat,
});
export const CommissionHistory = IDL.Record({
  'fundType' : FundType,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const FundToggle = IDL.Record({
  'isActive' : IDL.Bool,
  'fundType' : FundType,
});
export const UserProfile = IDL.Record({
  'commissionBalance' : IDL.Nat,
  'userId' : IDL.Text,
  'withdrawalRequests' : IDL.Vec(CommissionWithdrawal),
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'commissionHistory' : IDL.Vec(CommissionHistory),
  'banks' : IDL.Vec(BankAccount),
  'passwordHash' : IDL.Text,
  'registeredAt' : Time,
  'activatedFunds' : IDL.Vec(FundToggle),
});
export const Transaction = IDL.Record({
  'transactionType' : TransactionType,
  'userId' : IDL.Text,
  'fundType' : FundType,
  'amount' : IDL.Nat,
  'datetime' : Time,
  'transactionId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateFund' : IDL.Func([IDL.Text, FundType], [IDL.Bool], []),
  'activateFundsBatch' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, FundActivation))],
      [],
      [],
    ),
  'addBankAccount' : IDL.Func([IDL.Text, BankAccount], [], []),
  'addBankAccountWithFunds' : IDL.Func(
      [IDL.Text, BankAccount, IDL.Vec(FundType), IDL.Bool],
      [],
      [],
    ),
  'addCommissionEntry' : IDL.Func(
      [IDL.Text, FundType, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'addSupportLink' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addTransaction' : IDL.Func(
      [IDL.Text, IDL.Text, FundType, IDL.Nat, TransactionType],
      [IDL.Bool],
      [],
    ),
  'approveWithdrawal' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deactivateFund' : IDL.Func([IDL.Text, FundType], [IDL.Bool], []),
  'deleteUser' : IDL.Func([IDL.Text], [], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentUser' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getFundActivationCodes' : IDL.Func([], [IDL.Vec(FundActivation)], ['query']),
  'getNonAdminUser' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getSupportLink' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getTransactions' : IDL.Func([IDL.Text], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'requestWithdrawal' : IDL.Func(
      [IDL.Text, CommissionMethod, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'showToast' : IDL.Func([IDL.Text], [], []),
  'updateBankAccountStatus' : IDL.Func(
      [IDL.Text, IDL.Nat, AccountStatus],
      [],
      [],
    ),
  'useActivationCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'simpleRegister' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'simpleLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'adminSaveActivationCode' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'adminGetActivationCodes' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Record({'code': IDL.Text, 'fundType': IDL.Text, 'isUsed': IDL.Bool, 'usedBy': IDL.Text, 'createdAt': IDL.Int}))], ['query']),
    'adminDeleteActivationCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'simpleUseCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getSimpleActivatedFunds' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FundType = IDL.Variant({
    'mix' : IDL.Null,
    'gaming' : IDL.Null,
    'stock' : IDL.Null,
    'political' : IDL.Null,
  });
  const Time = IDL.Int;
  const FundActivation = IDL.Record({
    'usedByUserId' : IDL.Opt(IDL.Text),
    'code' : IDL.Text,
    'createdAt' : Time,
    'isUsed' : IDL.Bool,
    'fundType' : FundType,
  });
  const AccountStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const BankAccount = IDL.Record({
    'status' : AccountStatus,
    'ifscCode' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'bankName' : IDL.Text,
    'accountType' : IDL.Text,
    'upiId' : IDL.Text,
    'accountNumber' : IDL.Text,
    'accountHolder' : IDL.Text,
  });
  const TransactionType = IDL.Variant({
    'credit' : IDL.Null,
    'debit' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CommissionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
  });
  const CommissionMethod = IDL.Variant({
    'upi' : IDL.Null,
    'usdt' : IDL.Null,
    'bankTransfer' : IDL.Null,
  });
  const CommissionWithdrawal = IDL.Record({
    'id' : IDL.Text,
    'status' : CommissionStatus,
    'method' : CommissionMethod,
    'userId' : IDL.Text,
    'approvedAt' : IDL.Opt(Time),
    'createdAt' : Time,
    'amount' : IDL.Nat,
  });
  const CommissionHistory = IDL.Record({
    'fundType' : FundType,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const FundToggle = IDL.Record({
    'isActive' : IDL.Bool,
    'fundType' : FundType,
  });
  const UserProfile = IDL.Record({
    'commissionBalance' : IDL.Nat,
    'userId' : IDL.Text,
    'withdrawalRequests' : IDL.Vec(CommissionWithdrawal),
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'commissionHistory' : IDL.Vec(CommissionHistory),
    'banks' : IDL.Vec(BankAccount),
    'passwordHash' : IDL.Text,
    'registeredAt' : Time,
    'activatedFunds' : IDL.Vec(FundToggle),
  });
  const Transaction = IDL.Record({
    'transactionType' : TransactionType,
    'userId' : IDL.Text,
    'fundType' : FundType,
    'amount' : IDL.Nat,
    'datetime' : Time,
    'transactionId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateFund' : IDL.Func([IDL.Text, FundType], [IDL.Bool], []),
    'activateFundsBatch' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, FundActivation))],
        [],
        [],
      ),
    'addBankAccount' : IDL.Func([IDL.Text, BankAccount], [], []),
    'addBankAccountWithFunds' : IDL.Func(
        [IDL.Text, BankAccount, IDL.Vec(FundType), IDL.Bool],
        [],
        [],
      ),
    'addCommissionEntry' : IDL.Func(
        [IDL.Text, FundType, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'addSupportLink' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addTransaction' : IDL.Func(
        [IDL.Text, IDL.Text, FundType, IDL.Nat, TransactionType],
        [IDL.Bool],
        [],
      ),
    'approveWithdrawal' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deactivateFund' : IDL.Func([IDL.Text, FundType], [IDL.Bool], []),
    'deleteUser' : IDL.Func([IDL.Text], [], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentUser' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'getFundActivationCodes' : IDL.Func(
        [],
        [IDL.Vec(FundActivation)],
        ['query'],
      ),
    'getNonAdminUser' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'getSupportLink' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getTransactions' : IDL.Func([IDL.Text], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'requestWithdrawal' : IDL.Func(
        [IDL.Text, CommissionMethod, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'showToast' : IDL.Func([IDL.Text], [], []),
    'updateBankAccountStatus' : IDL.Func(
        [IDL.Text, IDL.Nat, AccountStatus],
        [],
        [],
      ),
    'useActivationCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'simpleRegister' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'simpleLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'adminSaveActivationCode' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'adminGetActivationCodes' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Record({'code': IDL.Text, 'fundType': IDL.Text, 'isUsed': IDL.Bool, 'usedBy': IDL.Text, 'createdAt': IDL.Int}))], ['query']),
    'adminDeleteActivationCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'simpleUseCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getSimpleActivatedFunds' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };