/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface BankAccount {
  'status' : AccountStatus,
  'ifscCode' : string,
  'mobileNumber' : string,
  'bankName' : string,
  'accountType' : string,
  'upiId' : string,
  'accountNumber' : string,
  'accountHolder' : string,
}
export interface CommissionHistory {
  'fundType' : FundType,
  'timestamp' : Time,
  'amount' : bigint,
}
export type CommissionMethod = { 'upi' : null } |
  { 'usdt' : null } |
  { 'bankTransfer' : null };
export type CommissionStatus = { 'pending' : null } |
  { 'approved' : null };
export interface CommissionWithdrawal {
  'id' : string,
  'status' : CommissionStatus,
  'method' : CommissionMethod,
  'userId' : string,
  'approvedAt' : [] | [Time],
  'createdAt' : Time,
  'amount' : bigint,
}
export interface FundActivation {
  'usedByUserId' : [] | [string],
  'code' : string,
  'createdAt' : Time,
  'isUsed' : boolean,
  'fundType' : FundType,
}
export interface FundToggle { 'isActive' : boolean, 'fundType' : FundType }
export type FundType = { 'mix' : null } |
  { 'gaming' : null } |
  { 'stock' : null } |
  { 'political' : null };
export type Time = bigint;
export interface Transaction {
  'transactionType' : TransactionType,
  'userId' : string,
  'fundType' : FundType,
  'amount' : bigint,
  'datetime' : Time,
  'transactionId' : string,
}
export type TransactionType = { 'credit' : null } |
  { 'debit' : null };
export interface UserProfile {
  'commissionBalance' : bigint,
  'userId' : string,
  'withdrawalRequests' : Array<CommissionWithdrawal>,
  'isActive' : boolean,
  'email' : string,
  'commissionHistory' : Array<CommissionHistory>,
  'banks' : Array<BankAccount>,
  'passwordHash' : string,
  'registeredAt' : Time,
  'activatedFunds' : Array<FundToggle>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateFund' : ActorMethod<[string, FundType], boolean>,
  'activateFundsBatch' : ActorMethod<
    [Array<[string, FundActivation]>],
    undefined
  >,
  'addBankAccount' : ActorMethod<[string, BankAccount], undefined>,
  'addBankAccountWithFunds' : ActorMethod<
    [string, BankAccount, Array<FundType>, boolean],
    undefined
  >,
  'addCommissionEntry' : ActorMethod<[string, FundType, bigint], boolean>,
  'addSupportLink' : ActorMethod<[string, string], undefined>,
  'addTransaction' : ActorMethod<
    [string, string, FundType, bigint, TransactionType],
    boolean
  >,
  'approveWithdrawal' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deactivateFund' : ActorMethod<[string, FundType], boolean>,
  'deleteUser' : ActorMethod<[string], undefined>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentUser' : ActorMethod<[string], [] | [UserProfile]>,
  'getFundActivationCodes' : ActorMethod<[], Array<FundActivation>>,
  'getNonAdminUser' : ActorMethod<[string], [] | [UserProfile]>,
  'getSupportLink' : ActorMethod<[string], [] | [string]>,
  'getTransactions' : ActorMethod<[string], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'register' : ActorMethod<[string, string], boolean>,
  'requestWithdrawal' : ActorMethod<
    [string, CommissionMethod, bigint],
    boolean
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'showToast' : ActorMethod<[string], undefined>,
  'updateBankAccountStatus' : ActorMethod<
    [string, bigint, AccountStatus],
    undefined
  >,
  'useActivationCode' : ActorMethod<[string], boolean>,
  'simpleRegister' : ActorMethod<[string, string], string>,
  'simpleLogin' : ActorMethod<[string, string], boolean>,
  'adminSaveActivationCode' : ActorMethod<[string, string, string], boolean>,
  'adminGetActivationCodes' : ActorMethod<[string], Array<{code: string; fundType: string; isUsed: boolean; usedBy: string; createdAt: bigint}>>,
  'adminDeleteActivationCode' : ActorMethod<[string, string], boolean>,
  'simpleUseCode' : ActorMethod<[string, string], string>,
  'getSimpleActivatedFunds' : ActorMethod<[string], Array<string>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];