/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CommissionHistory {
    fundType: FundType;
    timestamp: Time;
    amount: bigint;
}
export interface BankAccount {
    status: AccountStatus;
    ifscCode: string;
    mobileNumber: string;
    bankName: string;
    accountType: string;
    upiId: string;
    accountNumber: string;
    accountHolder: string;
}
export type Time = bigint;
export interface UserProfile {
    commissionBalance: bigint;
    userId: string;
    withdrawalRequests: Array<CommissionWithdrawal>;
    isActive: boolean;
    email: string;
    commissionHistory: Array<CommissionHistory>;
    banks: Array<BankAccount>;
    passwordHash: string;
    registeredAt: Time;
    activatedFunds: Array<FundToggle>;
}
export interface Transaction {
    transactionType: TransactionType;
    userId: string;
    fundType: FundType;
    amount: bigint;
    datetime: Time;
    transactionId: string;
}
export interface FundActivation {
    usedByUserId?: string;
    code: string;
    createdAt: Time;
    isUsed: boolean;
    fundType: FundType;
}
export interface FundToggle {
    isActive: boolean;
    fundType: FundType;
}
export interface CommissionWithdrawal {
    id: string;
    status: CommissionStatus;
    method: CommissionMethod;
    userId: string;
    approvedAt?: Time;
    createdAt: Time;
    amount: bigint;
}
export enum AccountStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum CommissionMethod {
    upi = "upi",
    usdt = "usdt",
    bankTransfer = "bankTransfer"
}
export enum CommissionStatus {
    pending = "pending",
    approved = "approved"
}
export enum FundType {
    mix = "mix",
    gaming = "gaming",
    stock = "stock",
    political = "political"
}
export enum TransactionType {
    credit = "credit",
    debit = "debit"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activateFund(userId: string, fundType: FundType): Promise<boolean>;
    activateFundsBatch(codes: Array<[string, FundActivation]>): Promise<void>;
    addBankAccount(userId: string, account: BankAccount): Promise<void>;
    addBankAccountWithFunds(userId: string, account: BankAccount, selectedFunds: Array<FundType>, isActive: boolean): Promise<void>;
    addCommissionEntry(userId: string, fundType: FundType, amount: bigint): Promise<boolean>;
    addSupportLink(key: string, link: string): Promise<void>;
    addTransaction(transactionId: string, userId: string, fundType: FundType, amount: bigint, transactionType: TransactionType): Promise<boolean>;
    approveWithdrawal(userId: string, withdrawalId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deactivateFund(userId: string, fundType: FundType): Promise<boolean>;
    deleteUser(userId: string): Promise<void>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentUser(userId: string): Promise<UserProfile | null>;
    getFundActivationCodes(): Promise<Array<FundActivation>>;
    getNonAdminUser(userId: string): Promise<UserProfile | null>;
    getSupportLink(key: string): Promise<string | null>;
    getTransactions(userId: string): Promise<Array<Transaction>>;
    getUserProfile(userPrincipal: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    register(email: string, passwordHash: string): Promise<boolean>;
    requestWithdrawal(userId: string, method: CommissionMethod, amount: bigint): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    showToast(_message: string): Promise<void>;
    updateBankAccountStatus(userId: string, accountIndex: bigint, status: AccountStatus): Promise<void>;
    useActivationCode(code: string): Promise<boolean>;
    simpleRegister(email: string, passwordHash: string): Promise<string>;
    simpleLogin(email: string, passwordHash: string): Promise<boolean>;
    adminSaveActivationCode(adminPassHash: string, code: string, fundType: string): Promise<boolean>;
    adminGetActivationCodes(adminPassHash: string): Promise<Array<{code: string; fundType: string; isUsed: boolean; usedBy: string; createdAt: bigint}>>;
    adminDeleteActivationCode(adminPassHash: string, code: string): Promise<boolean>;
    simpleUseCode(email: string, code: string): Promise<string>;
    getSimpleActivatedFunds(email: string): Promise<Array<string>>;
}
import type { AccountStatus as _AccountStatus, BankAccount as _BankAccount, CommissionHistory as _CommissionHistory, CommissionMethod as _CommissionMethod, CommissionStatus as _CommissionStatus, CommissionWithdrawal as _CommissionWithdrawal, FundActivation as _FundActivation, FundToggle as _FundToggle, FundType as _FundType, Time as _Time, Transaction as _Transaction, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activateFund(arg0: string, arg1: FundType): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.activateFund(arg0, to_candid_FundType_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateFund(arg0, to_candid_FundType_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async activateFundsBatch(arg0: Array<[string, FundActivation]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateFundsBatch(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateFundsBatch(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addBankAccount(arg0: string, arg1: BankAccount): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBankAccount(arg0, to_candid_BankAccount_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBankAccount(arg0, to_candid_BankAccount_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addBankAccountWithFunds(arg0: string, arg1: BankAccount, arg2: Array<FundType>, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBankAccountWithFunds(arg0, to_candid_BankAccount_n7(this._uploadFile, this._downloadFile, arg1), to_candid_vec_n11(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBankAccountWithFunds(arg0, to_candid_BankAccount_n7(this._uploadFile, this._downloadFile, arg1), to_candid_vec_n11(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async addCommissionEntry(arg0: string, arg1: FundType, arg2: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addCommissionEntry(arg0, to_candid_FundType_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCommissionEntry(arg0, to_candid_FundType_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async addSupportLink(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSupportLink(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSupportLink(arg0, arg1);
            return result;
        }
    }
    async addTransaction(arg0: string, arg1: string, arg2: FundType, arg3: bigint, arg4: TransactionType): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, arg1, to_candid_FundType_n1(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_TransactionType_n12(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, arg1, to_candid_FundType_n1(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_TransactionType_n12(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async approveWithdrawal(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawal(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deactivateFund(arg0: string, arg1: FundType): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateFund(arg0, to_candid_FundType_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateFund(arg0, to_candid_FundType_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentUser(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUser(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUser(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFundActivationCodes(): Promise<Array<FundActivation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFundActivationCodes();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFundActivationCodes();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNonAdminUser(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNonAdminUser(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNonAdminUser(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSupportLink(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupportLink(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupportLink(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactions(arg0: string): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions(arg0);
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions(arg0);
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async register(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1);
            return result;
        }
    }
    async requestWithdrawal(arg0: string, arg1: CommissionMethod, arg2: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0, to_candid_CommissionMethod_n52(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0, to_candid_CommissionMethod_n52(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n54(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n54(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async showToast(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.showToast(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.showToast(arg0);
            return result;
        }
    }
    async updateBankAccountStatus(arg0: string, arg1: bigint, arg2: AccountStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBankAccountStatus(arg0, arg1, to_candid_AccountStatus_n9(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBankAccountStatus(arg0, arg1, to_candid_AccountStatus_n9(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async useActivationCode(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.useActivationCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.useActivationCode(arg0);
            return result;
        }
    }
    async simpleRegister(email: string, passwordHash: string): Promise<string> {
        const result = await (this.actor as any).simpleRegister(email, passwordHash);
        return result;
    }
    async simpleLogin(email: string, passwordHash: string): Promise<boolean> {
        const result = await (this.actor as any).simpleLogin(email, passwordHash);
        return result;
    }
    async adminSaveActivationCode(adminPassHash: string, code: string, fundType: string): Promise<boolean> {
        const result = await (this.actor as any).adminSaveActivationCode(adminPassHash, code, fundType);
        return result;
    }
    async adminGetActivationCodes(adminPassHash: string): Promise<Array<{code: string; fundType: string; isUsed: boolean; usedBy: string; createdAt: bigint}>> {
        const result = await (this.actor as any).adminGetActivationCodes(adminPassHash);
        return result;
    }
    async adminDeleteActivationCode(adminPassHash: string, code: string): Promise<boolean> {
        const result = await (this.actor as any).adminDeleteActivationCode(adminPassHash, code);
        return result;
    }
    async simpleUseCode(email: string, code: string): Promise<string> {
        const result = await (this.actor as any).simpleUseCode(email, code);
        return result;
    }
    async getSimpleActivatedFunds(email: string): Promise<Array<string>> {
        const result = await (this.actor as any).getSimpleActivatedFunds(email);
        return result;
    }
}
function from_candid_AccountStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountStatus): AccountStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_BankAccount_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BankAccount): BankAccount {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_CommissionHistory_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommissionHistory): CommissionHistory {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_CommissionMethod_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommissionMethod): CommissionMethod {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_CommissionStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommissionStatus): CommissionStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_CommissionWithdrawal_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommissionWithdrawal): CommissionWithdrawal {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_FundActivation_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FundActivation): FundActivation {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_FundToggle_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FundToggle): FundToggle {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_FundType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FundType): FundType {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    commissionBalance: bigint;
    userId: string;
    withdrawalRequests: Array<_CommissionWithdrawal>;
    isActive: boolean;
    email: string;
    commissionHistory: Array<_CommissionHistory>;
    banks: Array<_BankAccount>;
    passwordHash: string;
    registeredAt: _Time;
    activatedFunds: Array<_FundToggle>;
}): {
    commissionBalance: bigint;
    userId: string;
    withdrawalRequests: Array<CommissionWithdrawal>;
    isActive: boolean;
    email: string;
    commissionHistory: Array<CommissionHistory>;
    banks: Array<BankAccount>;
    passwordHash: string;
    registeredAt: Time;
    activatedFunds: Array<FundToggle>;
} {
    return {
        commissionBalance: value.commissionBalance,
        userId: value.userId,
        withdrawalRequests: from_candid_vec_n19(_uploadFile, _downloadFile, value.withdrawalRequests),
        isActive: value.isActive,
        email: value.email,
        commissionHistory: from_candid_vec_n27(_uploadFile, _downloadFile, value.commissionHistory),
        banks: from_candid_vec_n32(_uploadFile, _downloadFile, value.banks),
        passwordHash: value.passwordHash,
        registeredAt: value.registeredAt,
        activatedFunds: from_candid_vec_n37(_uploadFile, _downloadFile, value.activatedFunds)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _CommissionStatus;
    method: _CommissionMethod;
    userId: string;
    approvedAt: [] | [_Time];
    createdAt: _Time;
    amount: bigint;
}): {
    id: string;
    status: CommissionStatus;
    method: CommissionMethod;
    userId: string;
    approvedAt?: Time;
    createdAt: Time;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_CommissionStatus_n22(_uploadFile, _downloadFile, value.status),
        method: from_candid_CommissionMethod_n24(_uploadFile, _downloadFile, value.method),
        userId: value.userId,
        approvedAt: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.approvedAt)),
        createdAt: value.createdAt,
        amount: value.amount
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fundType: _FundType;
    timestamp: _Time;
    amount: bigint;
}): {
    fundType: FundType;
    timestamp: Time;
    amount: bigint;
} {
    return {
        fundType: from_candid_FundType_n30(_uploadFile, _downloadFile, value.fundType),
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _AccountStatus;
    ifscCode: string;
    mobileNumber: string;
    bankName: string;
    accountType: string;
    upiId: string;
    accountNumber: string;
    accountHolder: string;
}): {
    status: AccountStatus;
    ifscCode: string;
    mobileNumber: string;
    bankName: string;
    accountType: string;
    upiId: string;
    accountNumber: string;
    accountHolder: string;
} {
    return {
        status: from_candid_AccountStatus_n35(_uploadFile, _downloadFile, value.status),
        ifscCode: value.ifscCode,
        mobileNumber: value.mobileNumber,
        bankName: value.bankName,
        accountType: value.accountType,
        upiId: value.upiId,
        accountNumber: value.accountNumber,
        accountHolder: value.accountHolder
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isActive: boolean;
    fundType: _FundType;
}): {
    isActive: boolean;
    fundType: FundType;
} {
    return {
        isActive: value.isActive,
        fundType: from_candid_FundType_n30(_uploadFile, _downloadFile, value.fundType)
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    usedByUserId: [] | [string];
    code: string;
    createdAt: _Time;
    isUsed: boolean;
    fundType: _FundType;
}): {
    usedByUserId?: string;
    code: string;
    createdAt: Time;
    isUsed: boolean;
    fundType: FundType;
} {
    return {
        usedByUserId: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.usedByUserId)),
        code: value.code,
        createdAt: value.createdAt,
        isUsed: value.isUsed,
        fundType: from_candid_FundType_n30(_uploadFile, _downloadFile, value.fundType)
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transactionType: _TransactionType;
    userId: string;
    fundType: _FundType;
    amount: bigint;
    datetime: _Time;
    transactionId: string;
}): {
    transactionType: TransactionType;
    userId: string;
    fundType: FundType;
    amount: bigint;
    datetime: Time;
    transactionId: string;
} {
    return {
        transactionType: from_candid_TransactionType_n50(_uploadFile, _downloadFile, value.transactionType),
        userId: value.userId,
        fundType: from_candid_FundType_n30(_uploadFile, _downloadFile, value.fundType),
        amount: value.amount,
        datetime: value.datetime,
        transactionId: value.transactionId
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
}): CommissionStatus {
    return "pending" in value ? CommissionStatus.pending : "approved" in value ? CommissionStatus.approved : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    usdt: null;
} | {
    bankTransfer: null;
}): CommissionMethod {
    return "upi" in value ? CommissionMethod.upi : "usdt" in value ? CommissionMethod.usdt : "bankTransfer" in value ? CommissionMethod.bankTransfer : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mix: null;
} | {
    gaming: null;
} | {
    stock: null;
} | {
    political: null;
}): FundType {
    return "mix" in value ? FundType.mix : "gaming" in value ? FundType.gaming : "stock" in value ? FundType.stock : "political" in value ? FundType.political : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): AccountStatus {
    return "pending" in value ? AccountStatus.pending : "approved" in value ? AccountStatus.approved : "rejected" in value ? AccountStatus.rejected : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    credit: null;
} | {
    debit: null;
}): TransactionType {
    return "credit" in value ? TransactionType.credit : "debit" in value ? TransactionType.debit : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CommissionWithdrawal>): Array<CommissionWithdrawal> {
    return value.map((x)=>from_candid_CommissionWithdrawal_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CommissionHistory>): Array<CommissionHistory> {
    return value.map((x)=>from_candid_CommissionHistory_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BankAccount>): Array<BankAccount> {
    return value.map((x)=>from_candid_BankAccount_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FundToggle>): Array<FundToggle> {
    return value.map((x)=>from_candid_FundToggle_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FundActivation>): Array<FundActivation> {
    return value.map((x)=>from_candid_FundActivation_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n48(_uploadFile, _downloadFile, x));
}
function to_candid_AccountStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountStatus): _AccountStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_BankAccount_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BankAccount): _BankAccount {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_CommissionHistory_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommissionHistory): _CommissionHistory {
    return to_candid_record_n63(_uploadFile, _downloadFile, value);
}
function to_candid_CommissionMethod_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommissionMethod): _CommissionMethod {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function to_candid_CommissionStatus_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommissionStatus): _CommissionStatus {
    return to_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function to_candid_CommissionWithdrawal_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommissionWithdrawal): _CommissionWithdrawal {
    return to_candid_record_n58(_uploadFile, _downloadFile, value);
}
function to_candid_FundActivation_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FundActivation): _FundActivation {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_FundToggle_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FundToggle): _FundToggle {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_FundType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FundType): _FundType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    commissionBalance: bigint;
    userId: string;
    withdrawalRequests: Array<CommissionWithdrawal>;
    isActive: boolean;
    email: string;
    commissionHistory: Array<CommissionHistory>;
    banks: Array<BankAccount>;
    passwordHash: string;
    registeredAt: Time;
    activatedFunds: Array<FundToggle>;
}): {
    commissionBalance: bigint;
    userId: string;
    withdrawalRequests: Array<_CommissionWithdrawal>;
    isActive: boolean;
    email: string;
    commissionHistory: Array<_CommissionHistory>;
    banks: Array<_BankAccount>;
    passwordHash: string;
    registeredAt: _Time;
    activatedFunds: Array<_FundToggle>;
} {
    return {
        commissionBalance: value.commissionBalance,
        userId: value.userId,
        withdrawalRequests: to_candid_vec_n56(_uploadFile, _downloadFile, value.withdrawalRequests),
        isActive: value.isActive,
        email: value.email,
        commissionHistory: to_candid_vec_n61(_uploadFile, _downloadFile, value.commissionHistory),
        banks: to_candid_vec_n64(_uploadFile, _downloadFile, value.banks),
        passwordHash: value.passwordHash,
        registeredAt: value.registeredAt,
        activatedFunds: to_candid_vec_n65(_uploadFile, _downloadFile, value.activatedFunds)
    };
}
function to_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: CommissionStatus;
    method: CommissionMethod;
    userId: string;
    approvedAt?: Time;
    createdAt: Time;
    amount: bigint;
}): {
    id: string;
    status: _CommissionStatus;
    method: _CommissionMethod;
    userId: string;
    approvedAt: [] | [_Time];
    createdAt: _Time;
    amount: bigint;
} {
    return {
        id: value.id,
        status: to_candid_CommissionStatus_n59(_uploadFile, _downloadFile, value.status),
        method: to_candid_CommissionMethod_n52(_uploadFile, _downloadFile, value.method),
        userId: value.userId,
        approvedAt: value.approvedAt ? candid_some(value.approvedAt) : candid_none(),
        createdAt: value.createdAt,
        amount: value.amount
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    usedByUserId?: string;
    code: string;
    createdAt: Time;
    isUsed: boolean;
    fundType: FundType;
}): {
    usedByUserId: [] | [string];
    code: string;
    createdAt: _Time;
    isUsed: boolean;
    fundType: _FundType;
} {
    return {
        usedByUserId: value.usedByUserId ? candid_some(value.usedByUserId) : candid_none(),
        code: value.code,
        createdAt: value.createdAt,
        isUsed: value.isUsed,
        fundType: to_candid_FundType_n1(_uploadFile, _downloadFile, value.fundType)
    };
}
function to_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fundType: FundType;
    timestamp: Time;
    amount: bigint;
}): {
    fundType: _FundType;
    timestamp: _Time;
    amount: bigint;
} {
    return {
        fundType: to_candid_FundType_n1(_uploadFile, _downloadFile, value.fundType),
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isActive: boolean;
    fundType: FundType;
}): {
    isActive: boolean;
    fundType: _FundType;
} {
    return {
        isActive: value.isActive,
        fundType: to_candid_FundType_n1(_uploadFile, _downloadFile, value.fundType)
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: AccountStatus;
    ifscCode: string;
    mobileNumber: string;
    bankName: string;
    accountType: string;
    upiId: string;
    accountNumber: string;
    accountHolder: string;
}): {
    status: _AccountStatus;
    ifscCode: string;
    mobileNumber: string;
    bankName: string;
    accountType: string;
    upiId: string;
    accountNumber: string;
    accountHolder: string;
} {
    return {
        status: to_candid_AccountStatus_n9(_uploadFile, _downloadFile, value.status),
        ifscCode: value.ifscCode,
        mobileNumber: value.mobileNumber,
        bankName: value.bankName,
        accountType: value.accountType,
        upiId: value.upiId,
        accountNumber: value.accountNumber,
        accountHolder: value.accountHolder
    };
}
function to_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, FundActivation]): [string, _FundActivation] {
    return [
        value[0],
        to_candid_FundActivation_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == AccountStatus.pending ? {
        pending: null
    } : value == AccountStatus.approved ? {
        approved: null
    } : value == AccountStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    credit: null;
} | {
    debit: null;
} {
    return value == TransactionType.credit ? {
        credit: null
    } : value == TransactionType.debit ? {
        debit: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FundType): {
    mix: null;
} | {
    gaming: null;
} | {
    stock: null;
} | {
    political: null;
} {
    return value == FundType.mix ? {
        mix: null
    } : value == FundType.gaming ? {
        gaming: null
    } : value == FundType.stock ? {
        stock: null
    } : value == FundType.political ? {
        political: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommissionMethod): {
    upi: null;
} | {
    usdt: null;
} | {
    bankTransfer: null;
} {
    return value == CommissionMethod.upi ? {
        upi: null
    } : value == CommissionMethod.usdt ? {
        usdt: null
    } : value == CommissionMethod.bankTransfer ? {
        bankTransfer: null
    } : value;
}
function to_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommissionStatus): {
    pending: null;
} | {
    approved: null;
} {
    return value == CommissionStatus.pending ? {
        pending: null
    } : value == CommissionStatus.approved ? {
        approved: null
    } : value;
}
function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FundType>): Array<_FundType> {
    return value.map((x)=>to_candid_FundType_n1(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, FundActivation]>): Array<[string, _FundActivation]> {
    return value.map((x)=>to_candid_tuple_n4(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CommissionWithdrawal>): Array<_CommissionWithdrawal> {
    return value.map((x)=>to_candid_CommissionWithdrawal_n57(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CommissionHistory>): Array<_CommissionHistory> {
    return value.map((x)=>to_candid_CommissionHistory_n62(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BankAccount>): Array<_BankAccount> {
    return value.map((x)=>to_candid_BankAccount_n7(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FundToggle>): Array<_FundToggle> {
    return value.map((x)=>to_candid_FundToggle_n66(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
